// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vymzvehgptvdfxvhjxhv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5bXp2ZWhncHR2ZGZ4dmhqeGh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MTE1OTEsImV4cCI6MjA3MTE4NzU5MX0.Z7UsdAlxFq2V9zIM79wv-P4GbLVnItUtM9hxJzGhVeE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});